# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the application
RUN npm run build

# Expose any relevant ports if necessary (default MCP may use stdio, so not needed here)

# Command to run the server
CMD ["node", "build/index.js"]
